version: '3.4'

services:
  sqldb:
    container_name: sqldb
    restart: always   
    ports:
      - "14333:1433"
    environment:
      SA_PASSWORD: "P12345_**"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
  elasticsearch:
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
  carcasetest.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqldb
      - elasticsearch
      - rabbitmq
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  elasticsearch-data: